### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Zehir** [cyr-ius/hass-livebox-component#107]
Hello,

I was trying to use the component to get info from a remote livebox but the web remote force https but without a valid certificate.

Is there any workaround for that issue ?

```
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiosysbus/auth.py", line 217, i
```

**Comment by cyr-ius** [comment]
Try last beta version , you an choice disable verify ssl

**Comment by Zehir** [comment]
Ty I will try next week when I can

**Comment by Zehir** [comment]
Hello, I tried with version : 2.3.5-beta1

And I am getting the same error;
![image](https://github.com/cyr-ius/hass-livebox-component/assets/845225/cd920ce2-4259-474c-8829-38de2cd55da5)

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1147, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1180, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiosysbus/auth.py", line 224, in _async_get_challenge
    response = await self.session.request(method="get", url=base_url.parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1029, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host ___IP_DEFINED_IN_UI___:____PORT_DEFINED_IN_UI____ ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiosysbus/aiosysbus.py", line 72, in async_connect
    await self._auth.async_get_session_token()
  File "/usr/local/lib/python3.12/site-packages/aiosysbus/auth.py", line 157, in async_get_session_token
    await self._async_get_challenge(self.base_url)
  File "/usr/local/lib/python3.12/site-packages/aiosysbus/auth.py", line 231, in _async_get_challenge
    raise HttpRequestFailed(
aiosysbus.exceptions.HttpRequestFailed: An error occurred while retrieving the challenge
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/livebox/config_flow.py", line 86, in async_step_user
    await api.async_connect()
  File "/usr/local/lib/python3.12/site-packages/aiosysbus/aiosysbus.py", line 76, in async_connect
    raise AiosysbusException(error) from error
aiosysbus.exceptions.AiosysbusException: An error occurred while retrieving the challenge
```

**Comment by Zehir** [comment]
Hello, I have still the issue with the version [2.3.5-beta1](https://github.com/cyr-ius/hass-livebox-component/releases/tag/2.3.5-beta1)
