### ISSUE TITLE
Connection problem with home assistant

### ISSUE THREAD

**Issue by eric97500** [cyr-ius/hass-livebox-component#160]
Hello, when I enter my login from my Livebox 7 I get error messages,

![livebox](https://github.com/user-attachments/assets/4c4514e7-00d3-4d0f-90b0-93d34464bfb7)

Logs details (ERROR) 

Logger: custom_components.livebox.coordinator
Source: helpers/update_coordinator.py:379
integration: Orange Livebox ([documentation](https://github.com/cyr-ius/hass-livebox-component), [issues](https://github.com/cyr-ius/hass-livebox-component/issues))
First occurred: 1:46:13 PM (14 occurrences)
Last logged: 1:50:18 PM
Unexpected error fetching livebox data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livebox/coordinator.py", line 72, in _async_update_data
    devices, device_counters = await self.async_get_devices(lan_tracking, wifi_tracking)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livebox/coordinator.py", line 114, in async_get_devices
    devices = await self._make_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
        self.api.devices.async_get_devices, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/livebox/coordinator.py", line 223, in _make_request
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/api/device.py", line 165, in async_get_devices
    return await self._auth.post("Devices", "get", conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/auth.py", line 143, in post
    return await self.async_request(method="post", json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/auth.py", line 124, in async_request
    rjson = await response.json()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 82, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1298, in json
    return loads(stripped.decode(encoding))
                 ~~~~~~~~~~~~~~~^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 92378: invalid continuation byte

Livebox 7 
Fabricant : Sagemcom
Version de firmware : G07.R02.C02_18
Version de firmware Orange : sbl-G7.R2.C2-fr 

Home assistant 
Core : 2024.12.5
Frontend : 20241127.8

Thank you for your help 

Sincerely 
Eric

**Comment by cyr-ius** [comment]
Please enable diagnostic logging and upload file

**Comment by Gacek74** [comment]
The application constantly disables internet access to Shelly devices.
[home-assistant_livebox_2025-01-17T18-59-32.028Z.log](https://github.com/user-attachments/files/18458855/home-assistant_livebox_2025-01-17T18-59-32.028Z.log)

**Comment by jerboyspy** [comment]
Hello since 2 week I have the same error with a livebox6
Impossible to Connect 

——
Livebox
Aucun appareil ou entité

Échec de la configuration, nouvel essai: 'utf-8' codec can't decode byte 0xe3 in position 98274: invalid continuation byte
——-


____—
Enregistreur: custom_components.livebox.coordinator
Source: helpers/update_coordinator.py:380
intégration: Orange Livebox ([documentation](https://github.com/cyr-ius/hass-livebox-component), [problèmes](https://github.com/cyr-ius/hass-livebox-component/issues))
S'est produit pour la première fois: 11:10:24 (41 occurrences)
Dernier enregistrement: 11:55:55

Unexpected error fetching livebox data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livebox/coordinator.py", line 77, in _async_update_data
    devices, device_counters = await self.async_get_devices(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lan_tracking, wifi_tracking
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/livebox/coordinator.py", line 121, in async_get_devices
    devices = await self._make_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
        self.api.devices.async_get_devices, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/livebox/coordinator.py", line 230, in _make_request
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/api/device.py", line 165, in async_get_devices
    return await self._auth.post("Devices", "get", conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/auth.py", line 143, in post
    return await self.async_request(method="post", json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/auth.py", line 124, in async_request
    rjson = await response.json()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 83, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1298, in json
    return loads(stripped.decode(encoding))
                 ~~~~~~~~~~~~~~~^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't dec

**Comment by jerboyspy** [comment]
The diagnostique log file :

<pre style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; overflow-wrap: break-word; white-space: pre-wrap;">^^^^^^^^^^^^^^^^^^^
        lan_tracking, wifi_tracking
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/livebox/coordinator.py", line 121, in async_get_devices
    devices = await self._make_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
        self.api.devices.async_get_devices, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/livebox/coordinator.py", line 230, in _make_request
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/api/device.py", line 165, in async_get_devices
    return await self._auth.post("Devices", "get", conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/auth.py", line 143, in post
    return await self.async_request(method="post", json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/auth.py", line 124, in async_request
    rjson = await response.json()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 83, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1298, in json
    return loads(stripped.decode(encoding))
                 ~~~~~~~~~~~~~~~^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 102163: invalid continuation byte
2025-02-15 11:27:14.026 DEBUG (MainThread) [custom_components.livebox.coordinator] Finished fetching livebox data in 1.488 seconds (success: False)
2025-02-15 11:28:34.425 DEBUG (MainThread) [aiosysbus.auth] Token JQDlWEN2gnCpUaEC2a9Ri1tB6Xw7uqQRT6uvixybxuE0xPPvCuiqHSYhyAzQcDMW
2025-02-15 11:28:34.426 DEBUG (MainThread) [aiosysbus.auth] METHOD:post URL:http://192.168.1.1/ws
2025-02-15 11:28:34.426 DEBUG (MainThread) [aiosysbus.auth] DATA:{'service': 'DeviceInfo', 'method': 'get', 'parameters': None}
2025-02-15 11:28:34.482 DEBUG (MainThread) [aiosysbus.auth] RESPONSE: {'status': {'Manufacturer': 'Sagemcom', 'ManufacturerOUI': 'ACD75B', 'ModelName': 'SagemcomFast5670E_OFR', 'Description': 'SagemcomFast5670E_OFR Sagemcom fr', 'ProductClass': 'Livebox 6', 'SerialNumber': 'JW23308SF043302', 'HardwareVersion': 'SG_LB6_1.1.0', 'SoftwareVersion': 'SG60-fr-G07.R02.C03_10', 'RescueVersion': 'SG60-fr-G07.R01.C02_06', 'ModemFirmwareVersion': '', 'EnabledOptions': '', 'AdditionalHardwareVersion': '', 'AdditionalSoftwareVersion': 'sbl-G7.R2.C3-fr', 'SpecVersion': '1.1', 'ProvisioningCode': 'HASH.7284.1390', 'UpTime': 147164, 'FirstUseDate': '0001-01-01T00:00:00Z', 'DeviceLog': '', 'VendorConfigFileNumberOfEntries': 1, 'ManufacturerURL': 'http://www.sagemcom.com/', 'Country': 'fr', 'ExternalIPAddress': '92.141.51.112', 'DeviceStatus': 'Up', 'NumberOfReboots': 22, 'UpgradeOccurred': False, 'ResetOccurred': False, 'RestoreOccurred': False, 'StandbyOccurred': False, 'X_SOFTATHOME-COM_AdditionalSoftwareVersions': '', 'BaseMAC': 'ac:d7:5b:36:4f:30'}}
2025-02-15 11:28:34.482 DEBUG (MainThread) [aiosysbus.auth] METHOD:post URL:http://192.168.1.1/ws
2025-02-15 11:28:34.482 DEBUG (MainThread) [aiosysbus.auth] DATA:{'service': 'Devices', 'method': 'get', 'parameters': {'expression': {'wifi': 'wifi &amp;&amp; (edev || hnid) and .PhysAddress!=""', 'eth': 'eth &amp;&amp; (edev || hnid) and .PhysAddress!=""'}}}
2025-02-15 11:28:35.864 ERROR (MainThread) [custom_components.livebox.coordinator] Unexpected error fetching livebox data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livebox/coordinator.py", line 77, in _async_update_data
    devices, device_counters = await self.async_get_devices(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lan_tracking, wifi_tracking
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/livebox/coordinator.py", line 121, in async_get_devices
    devices = await self._make_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
        self.api.devices.async_get_devices, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/livebox/coordinator.py", line 230, in _make_request
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/api/device.py", line 165, in async_get_devices
    return await self._auth.post("Devices", "get", conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/auth.py", line 143, in post
    return await self.async_request(method="post", json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/auth.py", line 124, in async_request
    rjson = await response.json()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 83, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1298, in json
    return loads(stripped.decode(encoding))
                 ~~~~~~~~~~~~~~~^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 102311: invalid continuation byte
2025-02-15 11:28:35.870 DEBUG (MainThread) [custom_components.livebox.coordinator] Finished fetching livebox data in 1.523 seconds (success: False)
2025-02-15 11:29:56.349 DEBUG (MainThread) [aiosysbus.auth] Token SjZxkUO0KN+fWiYUOesQHiD//Tvf877JWJgqEu+8up1jn5eEv/vnDYF80FqhMUaD
2025-02-15 11:29:56.349 DEBUG (MainThread) [aiosysbus.auth] METHOD:post URL:http://192.168.1.1/ws
2025-02-15 11:29:56.349 DEBUG (MainThread) [aiosysbus.auth] DATA:{'service': 'DeviceInfo', 'method': 'get', 'parameters': None}
2025-02-15 11:29:56.405 DEBUG (MainThread) [aiosysbus.auth] RESPONSE: {'status': {'Manufacturer': 'Sagemcom', 'ManufacturerOUI': 'ACD75B', 'ModelName': 'SagemcomFast5670E_OFR', 'Description': 'SagemcomFast5670E_OFR Sagemcom fr', 'ProductClass': 'Livebox 6', 'SerialNumber': 'JW23308SF043302', 'HardwareVersion': 'SG_LB6_1.1.0', 'SoftwareVersion': 'SG60-fr-G07.R02.C03_10', 'RescueVersion': 'SG60-fr-G07.R01.C02_06', 'ModemFirmwareVersion': '', 'EnabledOptions': '', 'AdditionalHardwareVersion': '', 'AdditionalSoftwareVersion': 'sbl-G7.R2.C3-fr', 'SpecVersion': '1.1', 'ProvisioningCode': 'HASH.7284.1390', 'UpTime': 147246, 'FirstUseDate': '0001-01-01T00:00:00Z', 'DeviceLog': '', 'VendorConfigFileNumberOfEntries': 1, 'ManufacturerURL': 'http://www.sagemcom.com/', 'Country': 'fr', 'ExternalIPAddress': '92.141.51.112', 'DeviceStatus': 'Up', 'NumberOfReboots': 22, 'UpgradeOccurred': False, 'ResetOccurred': False, 'RestoreOccurred': False, 'StandbyOccurred': False, 'X_SOFTATHOME-COM_AdditionalSoftwareVersions': '', 'BaseMAC': 'ac:d7:5b:36:4f:30'}}
2025-02-15 11:29:56.405 DEBUG (MainThread) [aiosysbus.auth] METHOD:post URL:http://192.168.1.1/ws
2025-02-15 11:29:56.405 DEBUG (MainThread) [aiosysbus.auth] DATA:{'service': 'Devices', 'method': 'get', 'parameters': {'expression': {'wifi': 'wifi &amp;&amp; (edev || hnid) and .PhysAddress!=""', 'eth': 'eth &amp;&amp; (edev || hnid) and .PhysAddress!=""'}}}
2025-02-15 11:29:57.774 ERROR (MainThread) [custom_components.livebox.coordinator] Unexpected error fetching livebox data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livebox/coordinator.py", line 77, in _async_update_data
    devices, device_counters = await self.async_get_devices(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lan_tracking, wifi_tracking
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/livebox/coordinator.py", line 121, in async_get_devices
    devices = await self._make_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
        self.api.devices.async_get_devices, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/livebox/coordinator.py", line 230, in _make_request
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/api/device.py", line 165, in async_get_devices
    return await self._auth.post("Devices", "get", conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/auth.py", line 143, in post
    return await self.async_request(method="post", json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiosysbus/auth.py", line 124, in async_request
    rjson = await response.json()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 83, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1298, in json
    return loads(stripped.decode(encoding))
                 ~~~~~~~~~~~~~~~^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 102034: invalid continuation byte
2025-02-15 11:29:57.780 DEBUG (MainThread) [custom_components.livebox.coordinator] Finished fetching livebox data in 1.509 seconds (success: False)</pre>
