### ISSUE TITLE
SyntaxError when launching HASS

### ISSUE THREAD

**Issue by tomtomdu85** [Cyr-ius/hass-livebox-component#20]
Hi

When my HASS starts, I've got this error :

```
Error setting up entry Livebox 4 for binary_sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 228, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/binary_sensor/__init__.py", line 139, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 146, in async_setup_entry
    platform_type,
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 298, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 402, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/house_bone/homeassistant/custom_components/livebox/binary_sensor.py", line 69
    if (cwired := self.coordinator.data.get("count_wired_devices")) > 0:
               ^
SyntaxError: invalid syntax
```

Have you got an idea ?

**Comment by CaronRemi** [comment]
Hello, I have the same problem.

**Comment by Cyr-ius** [comment]
Please update to 1.5.2
