### ISSUE TITLE
WanMode not found

### ISSUE THREAD

**Issue by tomtomdu85** [Cyr-ius/hass-livebox-component#26]
I've updated the livebox component, and now I've got this error :

2020-11-20 10:01:17 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up livebox platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/var/www/house_bone/homeassistant/custom_components/livebox/sensor.py", line 17, in async_setup_entry
    if "ETHERNET" not in nmc["WanMode"].upper():
KeyError: 'WanMode'

**Comment by Cyr-ius** [comment]
Fix 1.6.2
