### ISSUE TITLE
Erreur lors de l'utilisation de la fonction Reboot (Livebox V4)

### ISSUE THREAD

**Issue by ThibautLM** [Cyr-ius/hass-livebox-component#29]
Bonjour, 
Tout d'abord MERCI pour travail effectué. 

La fonctionnalité de reboot ne fonctionne pas lorsque j'essaye de l'utiliser. J'ai ces messages d'erreurs :  

Reboot Livebox: Error executing script. Unexpected error for call_service at pos 1: async_livebox_reboot() takes 0 positional arguments but 1 was given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 250, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 457, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
TypeError: async_livebox_reboot() takes 0 positional arguments but 1 was given

Merci d'avance

**Comment by Cyr-ius** [comment]
Corrigé voir version 1.5.5

**Comment by ThibautLM** [comment]
Merci c’est fonctionnel ! Super boulot !
