### ISSUE TITLE
Won't connect to livebox 4

### ISSUE THREAD

**Issue by tomtomdu85** [Cyr-ius/hass-livebox-component#33]
Hi

With the latest version 1.6.2, I've got this error :

Logger: homeassistant.config_entries
Source: custom_components/livebox/__init__.py:81
First occurred: 11:36:19 PM (1 occurrences)
Last logged: 11:36:19 PM

Error setting up entry Livebox 4 for livebox
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/var/www/house_bone/homeassistant/custom_components/livebox/__init__.py", line 81, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
AttributeError: 'DataUpdateCoordinator' object has no attribute 'async_config_entry_first_refresh'

Have you some ideas ?

Thanks in advance

Regards

**Comment by Cyr-ius** [comment]
You need a newer HomeAssistant version

**Comment by tomtomdu85** [comment]
I just update my HA. All it's great !

Thanks !
