### ISSUE TITLE
Component prevent HA to start

### ISSUE THREAD

**Issue by SNoof85** [Cyr-ius/hass-livebox-component#38]
HA version : 2021.9.3
Component version : 1.6.7

Trace : 
```
2021-09-06 21:05:39 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 322, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 314, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 108, in run
    return asyncio.run(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/src/homeassistant/homeassistant/runner.py", line 94, in setup_and_run_hass
    hass = await bootstrap.async_setup_hass(runtime_config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 118, in async_setup_hass
    config_dict = await conf_util.async_hass_config_yaml(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 364, in async_hass_config_yaml
    await merge_packages_config(hass, config, core_config.get(CONF_PACKAGES, {}))
  File "/usr/src/homeassistant/homeassistant/config.py", line 740, in merge_packages_config
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 516, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/livebox/__init__.py", line 14, in <module>
    from .bridge import BridgeData
  File "/config/custom_components/livebox/bridge.py", line 17, in <module>
    from .const import CALLID, CONF_LAN_TRACKING
  File "/config/custom_components/livebox/const.py", line 33, in <module>
    class FlowSensorEntityDescription(SensorEntityDescription):
  File "/config/custom_components/livebox/const.py", line 36, in FlowSensorEntityDescription
    current_rate: str | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
 ```

Disabled component and now HA starts good

**Comment by Cyr-ius** [comment]
Fix 1.6.8
