### ISSUE TITLE
Livebox 4 - Sensors Upload and Download unavailable (1.6.8)

### ISSUE THREAD

**Issue by xekil** [Cyr-ius/hass-livebox-component#39]
Hello,

Since I switched to Fiber and the livebox 4 was updated to version 4.15.10, the Upload and Download sensors are unavailable

https://github.com/Cyr-ius/hass-livebox-component/issues/37#issuecomment-913990575  Update 1.68 made but the problem is still there

Any ideas?

Thank you

Ha core - 2021.9.4
hass-livebox-component - 1.6.8

**Comment by SNoof85** [comment]
Here is the trace : 
```
Logger: homeassistant.components.binary_sensor
Source: custom_components/livebox/binary_sensor.py:61
Integration: Capteur binaire (documentation, issues)
First occurred: 23:38:10 (2 occurrences)
Last logged: 23:38:11

Error adding entities for domain binary_sensor with platform livebox
Error while setting up livebox platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/livebox/binary_sensor.py", line 61, in device_state_attributes
    uptime = datetime.today() - timedelta(
TypeError: unsupported type for timedelta seconds component: NoneType
```

**Comment by xekil** [comment]
@SNoof85 this log does not seem to be related to my problem, up and down are not binary sensors

**Comment by SNoof85** [comment]
My bad, new issue incoming then

**Comment by xekil** [comment]
Wifi sensors are same unavailable

**Comment by griffon56** [comment]
I have the same errors on my French Livebox fw : SG40_sip-fr-4.15.10.1_7.21.3.1
But the integration still runs fine

**Comment by Cyr-ius** [comment]
Fiber never goes up the speed
