### ISSUE TITLE
Livebox 4 issue since 1.6.9

### ISSUE THREAD

**Issue by griffon56** [Cyr-ius/hass-livebox-component#45]
Hello, since 1.6.9 update i get below error using orange (fr) livebox 4 :
Getting back to 1.6.8 and the error is gone.
```
Logger: homeassistant.config_entries
Source: custom_components/livebox/__init__.py:88
Integration: Orange Livebox (documentation, issues)
First occurred: 09:09:07 (1 occurrences)
Last logged: 09:09:07

Error setting up entry Livebox 4 for livebox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/livebox/__init__.py", line 88, in async_setup_entry
    device_registry.async_get_or_create(
TypeError: async_get_or_create() got an unexpected keyword argument 'configuration_url'
```

**Comment by griffon56** [comment]
after new upgrade trial it would work!
