### ISSUE TITLE
Error adding entities for domain binary_sensor.

### ISSUE THREAD

**Issue by WarC0zes** [Cyr-ius/hass-livebox-component#64]
Bonjour,
depuis la maj du core 2022.07.0, il y a ce message d'erreur. J'ai tout les device tracker qui sont indisponible et l'intégration a l'air cassé. 

```
2022-07-07 17:55:59 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform livebox
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
await self.async_added_to_hass()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 332, in async_added_to_hass
self._handle_coordinator_update, self.coordinator_context
AttributeError: 'CallMissed' object has no attribute 'coordinator_context'
```

**Comment by WarC0zes** [comment]
Après la maj en version 1.8.1, les devices trackers sont revenu. Mais il y a des sensors qui sont encore indisponible
![livebox sensor](https://user-images.githubusercontent.com/91471397/178151177-bc62ebe9-3ab5-4a58-a71d-792d9c715be9.png)

Le service Orange Livebox: remove_call_missed fonctionne, mais on recois un message d'avertissement en bas a gauche.
![livebox erreur](https://user-images.githubusercontent.com/91471397/178151269-c0038cf8-ef3b-4c85-bc51-8f382dbb7481.png)


Merci pour les maj dernières ;)

**Comment by WarC0zes** [comment]
Après la maj du core 2022.07.3 et un reboot, j'ai l'entité binary_sensor.wan_status qui est redevenu opérationnelle. Mais les buttons ne fonctionnent pas et les entitées donwload / upload.
![livebox 2022 07 3](https://user-images.githubusercontent.com/91471397/178241411-a52bc646-317e-48c4-b37d-0576907c328e.png)

J'ai c'est erreur qui reviens souvent, en 24h j'ai eu plus de 700 occurences.
```
Logger: homeassistant
Source: custom_components/livebox/sensor.py:57
Integration: Orange Livebox ([documentation](https://github.com/cyr-ius/hass-livebox-component), [issues](https://github.com/cyr-ius/hass-livebox-component/issues))
First occurred: 11:42:04 (25 occurrences)
Last logged: 12:07:22

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 339, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/livebox/sensor.py", line 57, in extra_state_attributes
    _attributs[key] = self.coordinator.data["dsl_status"].get(value)
NameError: name '_attributs' is not defined

```

**Comment by Cyr-ius** [comment]
Fix with 1.8.2

**Comment by WarC0zes** [comment]
Tout refonctionne avec la version 1.8.2. Merci @Cyr-ius
