### ISSUE TITLE
Version 1.8.3 

### ISSUE THREAD

**Issue by LGO44** [Cyr-ius/hass-livebox-component#72]
Après installation de cette version  j'obtiens le message 
Error occurred loading configuration flow for integration livebox: Exception importing custom_components.livebox.config_flow
10:40:43 – (ERREUR) config_entries.py - message survenu pour la première fois à 10:35:05 et apparu 2 fois.
Unexpected exception importing platform custom_components.livebox.config_flow
10:40:43 – (ERREUR) Orange Livebox (intégration personnalisée) - message survenu pour la première fois à 10:35:05 et apparu 2 fois.

Après désinstallation puis réinstallation j'obtiens
Le flux de configuration n'a pas pu être chargé: {"message":"Invalid handler specified"}

**Comment by chatainsim** [comment]
Hello, j'ai aussi une erreur avec la dernière version.
Cette erreur provient d'une intégration personnalisée

```Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.loader
Source: custom_components/livebox/__init__.py:67
Integration: Orange Livebox (documentation, issues)
First occurred: 11:09:22 (1 occurrences)
Last logged: 11:09:22

Unexpected exception importing component custom_components.livebox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 730, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/livebox/__init__.py", line 67, in <module>
    async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
NameError: name 'ConfigEntry' is not defined
```

**Comment by hugoKs3** [comment]
Issue #70 déjà ouverte pour ce problème et PR #71 proposée pour la correction (+ fontionnalité pour le Wifi Guest)
@Cyr-ius, possibilité de merger au plus vite ?

**Comment by Cyr-ius** [comment]
La nouvelle version est disponible 1.8.5

**Comment by LGO44** [comment]
Merci ça marche
